### ISSUE TITLE
AttributeError: module 'otbtf' has no attribute 'layers' in training.py

### ISSUE THREAD

**Issue by RaphaelDutrieux** [remicres/otbtf_keras_tutorial#1]
En suivant le tutoriel, j'ai l'erreur suivante en essayant de faire tourner training.py :

Traceback (most recent call last):
  File "/data/code/training.py", line 147, in <module>
    train(params, ds_train, ds_valid, ds_test)
  File "/data/code/training.py", line 94, in train
    model = FCNNModel(dataset_element_spec=ds_train.element_spec)
  File "/src/otbtf/otbtf/model.py", line 86, in __init__
    self.model = self.create_network()
  File "/src/otbtf/otbtf/model.py", line 220, in create_network
    outputs = self.get_outputs(normalized_inputs=normalized_inputs)
  File "/data/code/training.py", line 86, in get_outputs
    argmax_op = otbtf.layers.Argmax(name="argmax_layer")
AttributeError: module 'otbtf' has no attribute 'layers'

**Comment by remicres** [comment]
check otbtf version, it has to be at least 4.1.0

**Comment by RaphaelDutrieux** [comment]
otbtf version is 4.1.0, I'm using the docker image.

**Comment by remicres** [comment]
My bad, the required version for the tutorial should be at least 4.2.0.

New python classes and stuff have been added (`otbtf.ops` and `otbtf.layers`). New docker images are on the way...
